//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Smart.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fac
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FK_uniId { get; set; }
    
        public virtual Uni Uni { get; set; }
    }
}
